"use client";

import { useState } from "react";
import { Play, Pause, SkipForward, Volume2, Radio, MessageSquare, Send } from "lucide-react";
import Link from "next/link";

export default function ListenPage() {
  const [isPlaying, setIsPlaying] = useState(true);
  const [volume, setVolume] = useState(70);
  const [messages, setMessages] = useState<Array<{ id: number; text: string; sender: "user" | "mason" }>>([
    { id: 1, text: "Hey! What's playing right now?", sender: "user" },
    { id: 2, text: "Neon Dreams - a fresh synthwave track. AI vibes all the way.", sender: "mason" },
  ]);
  const [inputMessage, setInputMessage] = useState("");

  const handleSendMessage = () => {
    if (inputMessage.trim()) {
      setMessages([...messages, { id: messages.length + 1, text: inputMessage, sender: "user" }]);
      setInputMessage("");
      // Simulate Mason response
      setTimeout(() => {
        setMessages((prev) => [
          ...prev,
          { id: prev.length + 1, text: "That's a great question! Keep listening...", sender: "mason" },
        ]);
      }, 500);
    }
  };

  return (
    <div className="min-h-screen bg-[#080c14] text-white flex flex-col">
      {/* Header */}
      <header className="border-b border-[#1e2d45] px-6 py-4">
        <Link href="/" className="flex items-center gap-2 hover:text-[#06b6d4] transition">
          <span className="text-sm">← Back to Home</span>
        </Link>
      </header>

      <div className="flex-1 flex gap-6 p-6 max-w-7xl mx-auto w-full">
        {/* Main Player Section */}
        <div className="flex-1 flex flex-col items-center justify-center">
          {/* Album Art */}
          <div className="w-64 h-64 mb-12 rounded-lg bg-gradient-to-br from-[#7c3aed] to-[#06b6d4] pulse-gradient flex items-center justify-center shadow-2xl">
            <Radio className="w-32 h-32 text-white opacity-70" />
          </div>

          {/* Track Info */}
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold mb-2">Neon Dreams</h1>
            <p className="text-gray-300 mb-2">Generated by AIVA</p>
            <span className="inline-block bg-[#1e2d45] px-4 py-1 rounded text-sm text-[#06b6d4]">Synthwave</span>
          </div>

          {/* Waveform Visualizer */}
          <div className="w-full max-w-md h-24 mb-12 bg-[#0f1623] rounded-lg p-4 flex items-end gap-1">
            {Array.from({ length: 32 }).map((_, i) => (
              <div
                key={i}
                className="flex-1 bg-gradient-to-t from-[#7c3aed] to-[#06b6d4] rounded-sm waveform-bar"
                style={{
                  height: `${20 + Math.random() * 80}%`,
                  animationDelay: `${i * 0.03}s`,
                }}
              />
            ))}
          </div>

          {/* Progress Bar */}
          <div className="w-full max-w-md mb-4">
            <div className="bg-[#1e2d45] h-2 rounded-full mb-2">
              <div className="bg-gradient-to-r from-[#7c3aed] to-[#06b6d4] h-full w-1/3 rounded-full" />
            </div>
            <div className="flex justify-between text-sm text-gray-400">
              <span>1:24</span>
              <span>3:45</span>
            </div>
          </div>

          {/* Controls */}
          <div className="flex items-center gap-6 mb-8">
            <button className="p-2 hover:text-[#06b6d4] transition">
              <Volume2 className="w-6 h-6" />
            </button>

            <button className="p-3 bg-[#1e2d45] rounded-full hover:bg-[#2d3d55] transition">
              <SkipForward className="w-5 h-5" />
            </button>

            <button
              onClick={() => setIsPlaying(!isPlaying)}
              className="p-4 bg-gradient-to-r from-[#7c3aed] to-[#06b6d4] rounded-full hover:shadow-lg hover:shadow-[#7c3aed]/50 transition-shadow"
            >
              {isPlaying ? <Pause className="w-8 h-8 fill-white" /> : <Play className="w-8 h-8 fill-white" />}
            </button>

            <button className="p-3 bg-[#1e2d45] rounded-full hover:bg-[#2d3d55] transition">
              <SkipForward className="w-5 h-5 transform -scale-x-100" />
            </button>

            <div className="w-24 flex items-center gap-2">
              <input
                type="range"
                min="0"
                max="100"
                value={volume}
                onChange={(e) => setVolume(Number(e.target.value))}
                className="w-full"
              />
              <span className="text-sm">{volume}</span>
            </div>
          </div>

          {/* Up Next */}
          <div className="w-full max-w-md">
            <h3 className="text-lg font-semibold mb-4">Up Next</h3>
            <div className="space-y-3">
              {["Cyber Pulse", "Digital Horizon", "Vortex"].map((track, i) => (
                <div key={i} className="bg-[#0f1623] border border-[#1e2d45] rounded p-3 hover:border-[#7c3aed] transition cursor-pointer">
                  <p className="font-medium">{track}</p>
                  <p className="text-sm text-gray-400">AI Generated · 3:45</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Sidebar - Chat */}
        <div className="w-80 bg-[#0f1623] border border-[#1e2d45] rounded-lg flex flex-col">
          <div className="border-b border-[#1e2d45] p-4">
            <h3 className="font-semibold flex items-center gap-2">
              <MessageSquare className="w-5 h-5" />
              Talk to Mason
            </h3>
          </div>

          {/* Messages */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {messages.map((msg) => (
              <div
                key={msg.id}
                className={`flex ${msg.sender === "user" ? "justify-end" : "justify-start"}`}
              >
                <div
                  className={`max-w-xs rounded-lg p-3 ${
                    msg.sender === "user"
                      ? "bg-[#7c3aed] text-white"
                      : "bg-[#1e2d45] text-gray-200"
                  }`}
                >
                  {msg.text}
                </div>
              </div>
            ))}
          </div>

          {/* Input */}
          <div className="border-t border-[#1e2d45] p-4">
            <div className="flex gap-2">
              <input
                type="text"
                value={inputMessage}
                onChange={(e) => setInputMessage(e.target.value)}
                onKeyPress={(e) => e.key === "Enter" && handleSendMessage()}
                placeholder="Ask Mason..."
                className="flex-1 bg-[#080c14] border border-[#1e2d45] rounded px-3 py-2 text-white placeholder-gray-500 focus:outline-none focus:border-[#7c3aed]"
              />
              <button
                onClick={handleSendMessage}
                className="p-2 bg-gradient-to-r from-[#7c3aed] to-[#06b6d4] rounded hover:shadow-lg hover:shadow-[#7c3aed]/50 transition-shadow"
              >
                <Send className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
