"use client";

import { Play, Volume2 } from "lucide-react";

export function PlayerCard() {
  return (
    <div className="bg-[#0f1623] border border-[#1e2d45] rounded-lg p-6 max-w-md mx-auto mb-8 backdrop-blur">
      <div className="text-sm text-gray-400 mb-2">NOW PLAYING</div>
      <h3 className="text-2xl font-semibold mb-1">Neon Dreams</h3>
      <p className="text-gray-400 mb-6">Generated by AIVA · Synthwave</p>

      {/* Waveform bars */}
      <div className="flex items-end gap-1 h-16 mb-6 bg-[#080c14]/50 rounded p-4">
        {Array.from({ length: 24 }).map((_, i) => (
          <div
            key={i}
            className="flex-1 bg-gradient-to-t from-[#7c3aed] to-[#06b6d4] rounded-sm waveform-bar"
            style={{
              height: `${Math.random() * 100}%`,
              animationDelay: `${i * 0.05}s`,
            }}
          />
        ))}
      </div>

      {/* Controls */}
      <div className="flex items-center justify-between">
        <button className="p-3 bg-gradient-to-r from-[#7c3aed] to-[#06b6d4] rounded-full hover:shadow-lg hover:shadow-[#7c3aed]/50 transition-shadow">
          <Play className="w-6 h-6 fill-white" />
        </button>
        
        <div className="flex-1 mx-4">
          <div className="bg-[#1e2d45] h-1 rounded-full">
            <div className="bg-gradient-to-r from-[#7c3aed] to-[#06b6d4] h-full w-1/3 rounded-full" />
          </div>
          <div className="flex justify-between text-xs text-gray-400 mt-1">
            <span>1:24</span>
            <span>3:45</span>
          </div>
        </div>

        <button className="p-2 hover:text-[#06b6d4] transition">
          <Volume2 className="w-5 h-5" />
        </button>
      </div>
    </div>
  );
}
