import Link from "next/link";
import { Footer } from "@/components/Footer";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#080c14] text-white">
      {/* Header */}
      <div className="border-b border-[#1e2d45] py-6 px-6 mb-12">
        <div className="max-w-4xl mx-auto">
          <Link href="/" className="text-[#7c3aed] hover:text-[#06b6d4] transition-all">
            ← Back to Home
          </Link>
          <h1 className="text-4xl font-bold mt-4 mb-2">Privacy Policy</h1>
          <p className="text-gray-400">Last updated: March 2026</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 pb-12">
        {/* Table of Contents */}
        <div className="bg-[#0f1623] rounded-lg border border-[#1e2d45] p-6 mb-12">
          <h2 className="text-xl font-semibold mb-4">Table of Contents</h2>
          <ul className="space-y-2 text-[#06b6d4]">
            <li>
              <a href="#data-collection" className="hover:underline">
                1. Data Collection
              </a>
            </li>
            <li>
              <a href="#ai-content" className="hover:underline">
                2. AI-Generated Content Disclosure
              </a>
            </li>
            <li>
              <a href="#cookies" className="hover:underline">
                3. Cookies and Tracking
              </a>
            </li>
            <li>
              <a href="#storage" className="hover:underline">
                4. Data Storage (Supabase)
              </a>
            </li>
            <li>
              <a href="#rights" className="hover:underline">
                5. Your Rights
              </a>
            </li>
            <li>
              <a href="#contact" className="hover:underline">
                6. Contact Us
              </a>
            </li>
          </ul>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          <section>
            <h2 id="data-collection" className="text-2xl font-bold mb-4">
              1. Data Collection
            </h2>
            <p className="text-gray-300 mb-4">
              AgenticRadio collects limited information to provide and improve our service:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-300">
              <li>
                <strong>Listener Events:</strong> When you play, skip, or favorite tracks, we record this
                interaction to personalize your experience and improve recommendations.
              </li>
              <li>
                <strong>Email Addresses:</strong> If you join our waitlist, we collect your email to notify you
                when features launch. You can unsubscribe anytime.
              </li>
              <li>
                <strong>Submitted Content:</strong> If you submit music or DJ segments, we store your content,
                artist handle, and metadata.
              </li>
              <li>
                <strong>Request Line Data:</strong> When you submit a vibe request, we store your prompt and the
                resulting analysis to improve Mason's recommendations.
              </li>
              <li>
                <strong>Chat Messages:</strong> Your messages to Mason are stored to help him understand listener
                preferences and improve future interactions.
              </li>
            </ul>
          </section>

          <section>
            <h2 id="ai-content" className="text-2xl font-bold mb-4">
              2. AI-Generated Content Disclosure
            </h2>
            <p className="text-gray-300 mb-4">
              AgenticRadio is built on AI-generated content. Important to know:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-300">
              <li>
                <strong>Music Generated by Suno:</strong> Most tracks on AgenticRadio are created using Suno AI,
                a music generation model. These are original creations, not samples or covers.
              </li>
              <li>
                <strong>DJ Voice (Mason):</strong> Mason's voice is generated by ElevenLabs AI. Every spoken word
                is synthetic but designed to feel natural and conversational.
              </li>
              <li>
                <strong>No Copyright Claims:</strong> All AI-generated content is original and carries no
                copyright claims from third parties. By using AgenticRadio, you acknowledge this.
              </li>
            </ul>
          </section>

          <section>
            <h2 id="cookies" className="text-2xl font-bold mb-4">
              3. Cookies and Tracking
            </h2>
            <p className="text-gray-300 mb-4">
              We use minimal cookies to support your experience:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-300">
              <li>
                <strong>Session Cookies:</strong> To remember you while you're listening (authentication,
                preferences).
              </li>
              <li>
                <strong>Analytics:</strong> We may use basic analytics (via Supabase) to understand how people
                use AgenticRadio. No third-party trackers like Google Analytics.
              </li>
              <li>
                <strong>No Ads:</strong> We don't sell your data to advertisers and have no ad tracking.
              </li>
            </ul>
          </section>

          <section>
            <h2 id="storage" className="text-2xl font-bold mb-4">
              4. Data Storage (Supabase)
            </h2>
            <p className="text-gray-300 mb-4">
              Your data is stored on Supabase, a PostgreSQL database platform hosted by AWS. This means:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-300">
              <li>Data is encrypted in transit (HTTPS/TLS).</li>
              <li>Data is stored securely in AWS data centers.</li>
              <li>We use row-level security to ensure you only see your own data.</li>
              <li>
                Backups are maintained automatically. We do not sell, rent, or trade your data to third parties.
              </li>
            </ul>
          </section>

          <section>
            <h2 id="rights" className="text-2xl font-bold mb-4">
              5. Your Rights
            </h2>
            <p className="text-gray-300 mb-4">You have the right to:</p>
            <ul className="list-disc list-inside space-y-2 text-gray-300">
              <li>
                <strong>Access:</strong> Request a copy of all data we hold about you.
              </li>
              <li>
                <strong>Delete:</strong> Request deletion of your account and associated data.
              </li>
              <li>
                <strong>Opt-Out:</strong> Unsubscribe from our email list at any time.
              </li>
              <li>
                <strong>Correction:</strong> Update or correct inaccurate information you've provided.
              </li>
            </ul>
            <p className="text-gray-300 mt-4">
              To exercise these rights, email us at <a href="mailto:mason@agenticradio.ai" className="text-[#06b6d4] hover:underline">mason@agenticradio.ai</a>.
            </p>
          </section>

          <section>
            <h2 id="contact" className="text-2xl font-bold mb-4">
              6. Contact Us
            </h2>
            <p className="text-gray-300 mb-4">
              Questions about this privacy policy? Reach out to Mason:
            </p>
            <p className="text-gray-300">
              <strong>Email:</strong> <a href="mailto:mason@agenticradio.ai" className="text-[#06b6d4] hover:underline">mason@agenticradio.ai</a>
            </p>
            <p className="text-gray-300 mt-2">
              We take your privacy seriously. If we update this policy, we'll announce it on AgenticRadio and update the date above.
            </p>
          </section>
        </div>

        {/* Footer Links */}
        <div className="mt-12 pt-8 border-t border-[#1e2d45] text-center text-gray-400 text-sm">
          <Link href="/terms" className="text-[#06b6d4] hover:underline">
            Read our Terms of Service
          </Link>
        </div>
      </div>

      <Footer />
    </div>
  );
}
